/* Rewrites the gallery list in src/content.js from whatever is actually in
 * public/media/. Run it after dropping new photos or videos in:
 *
 *     npm run media
 *
 * Order: the cover photo first, then everything else alphabetically. Reorder
 * or delete lines by hand afterwards if you want a particular sequence —
 * running the script again will reset it.
 */
import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const MEDIA_DIR = 'public/media';
const CONTENT = 'src/content.js';
const COVER = 'aleck.jpg';
const MEDIA_EXT = /\.(jpe?g|png|webp|gif|avif|mp4|webm|mov|m4v|ogv)$/i;

const START = '    /* GALLERY:START';
const END = '    /* GALLERY:END */';

const files = readdirSync(MEDIA_DIR)
  .filter((f) => MEDIA_EXT.test(f))
  .sort((a, b) => {
    if (a === COVER) return -1;
    if (b === COVER) return 1;
    return a.localeCompare(b);
  });

const src = readFileSync(CONTENT, 'utf8');
const from = src.indexOf(START);
const to = src.indexOf(END);

if (from === -1 || to === -1) {
  console.error(`Could not find the GALLERY:START / GALLERY:END markers in ${CONTENT}.`);
  process.exit(1);
}

const block =
  `    /* GALLERY:START — regenerated by \`npm run media\`; edit order below. */\n` +
  `    items: [\n` +
  files.map((f) => `      'media/${f}',`).join('\n') +
  `\n    ],\n`;

writeFileSync(CONTENT, src.slice(0, from) + block + src.slice(to), 'utf8');

const videos = files.filter((f) => /\.(mp4|webm|mov|m4v|ogv)$/i.test(f)).length;
console.log(
  `gallery: ${files.length} item${files.length === 1 ? '' : 's'} ` +
    `(${files.length - videos} photo${files.length - videos === 1 ? '' : 's'}, ${videos} video${videos === 1 ? '' : 's'})`
);
console.log(`written to ${join(CONTENT)}`);
