/* ============================================================================
 *  THIS IS THE ONLY FILE YOU NEED TO EDIT
 * ----------------------------------------------------------------------------
 *  Everything the site shows her comes from here. Replace the placeholder text
 *  below with your own. Nothing else in the project needs to be touched.
 *
 *  PHOTOS / VIDEOS / SONG:
 *    Drop the files into the  public/media/  folder, then reference them as
 *    "media/your-file.jpg" (no leading slash) in the lists below.
 * ==========================================================================*/

export const content = {
  /* ---- WHO ------------------------------------------------------------- */
  herName: 'ALECK',
  yourName: 'YOUR NAME',

  /* ---- TITLE SCREEN ---------------------------------------------------- */
  title: {
    line1: 'HAPPY',
    line2: 'BIRTHDAY',
    tagline: 'A LITTLE SOMETHING I MADE FOR YOU',
    pressStart: 'PRESS START',
  },

  /* ---- PIN LOCK -------------------------------------------------------- */
  lock: {
    // The date you two first met, as MMDD. August 29 -> '0829'
    pin: '0829',
    prompt: 'ENTER THE DATE WE MET',
    wrong: 'WRONG. TRY AGAIN.',
    hint: 'HINT: THE DAY WE FIRST MET.',
    success: 'ACCESS GRANTED',
    lockedOut: 'OUT OF LIVES... BUT I KNOW YOU KNOW THIS ONE.',
  },

  /* ---- MAIN MENU ------------------------------------------------------- */
  menu: {
    heading: 'SELECT A LEVEL',
    footer: 'MADE WITH TOO MANY PIXELS AND ONE BIG CRUSH',
    items: {
      gallery: { label: 'GALLERY', sub: 'PHOTOS AND VIDEOS OF YOU' },
      message: { label: 'MESSAGE', sub: 'WHAT I WANT TO SAY' },
      /* {n} is replaced with however many reasons are in the list below, so
       * this label can never drift out of date again. */
      song: { label: 'SONG DEDICATED FOR YOU', sub: 'PLAY IT LOUD' },
      reasons: { label: '{n} REASONS WHY I LIKE YOU', sub: 'TAP EACH ONE TO UNLOCK' },
    },
  },

  /* ---- GALLERY ---------------------------------------------------------- */
  gallery: {
    heading: 'GALLERY',

    /* Slideshow pace in milliseconds. Lower = faster. */
    slideshowMs: 1800,
    /* How often the self-running spotlight moves to the next photo. */
    spotlightMs: 1900,

    /* GALLERY:START — regenerated by `npm run media`; edit order below. */
    items: [
      'media/aleck.jpg',
      'media/024dad42-c416-4713-8b9b-cb304f79308e.jpg',
      'media/094f164a-a720-4bd9-bfe8-023dd096e6ae.jpg',
      'media/0d7370e7-e966-4755-ae59-4211e7dec0db.jpg',
      'media/13ea596b-86a2-46c9-a766-f06d2bd4529a.jpg',
      'media/144e4d88-475a-41b2-836c-9a0a4621cce6.jpg',
      'media/15b79dda-f832-4a97-a80d-cba113deae6c.jpg',
      'media/23862eee-97a6-486d-adde-d39d3af517f8.jpg',
      'media/28b355ea-4423-4349-99d6-e6b382df15cd.jpg',
      'media/31fc9f9a-6f03-4fa8-a564-2a4b0694a5f6.jpg',
      'media/324035d5-348b-4d89-b984-fdd37b36395b.jpg',
      'media/34bafca4-5a87-4b5d-930c-37eeafc0cd21.jpg',
      'media/4b427a5d-94f5-49e2-ae83-85023c16a63b.jpg',
      'media/4b4e24cc-c7ee-4c43-92f8-2baa41053260.jpg',
      'media/4fbd8207-c27b-4359-9c1f-21a29412e89f.jpg',
      'media/5c646e1e-717e-453b-b80f-8f1cd7191ca4.jpg',
      'media/6043edd5-8137-404c-b83f-0bafc35a8827.jpg',
      'media/60952b68-65a1-44a9-89b6-e959c211a5f9.jpg',
      'media/6a55f5e3-de92-4f48-ad79-8931265a457c.jpg',
      'media/70218ef4-b6cc-4630-8299-994769041382.jpg',
      'media/71b04cb7-d9ba-42cb-9cbc-edcb0e3c8ed7.jpg',
      'media/7994a592-83cd-44d2-9e91-bd3c13084072.jpg',
      'media/810c409a-0fde-4db7-9756-61c342795235.jpg',
      'media/872756cb-db81-422e-a36e-aaf77100fe5e.jpg',
      'media/928850a1-c45f-46c5-a1ad-9ff3ac9d4987.jpg',
      'media/945b4f18-c9bb-4aef-9df2-fa0a31847d6f.jpg',
      'media/94f52225-576c-45bc-aa1f-00f7a8fb10ed.jpg',
      'media/978bfd39-8691-4524-95b4-cbc61a93d842.jpg',
      'media/97e5ae61-e994-4f7e-9c15-84641304b0a1.jpg',
      'media/99798f72-34e0-4fe6-9882-8bf95361d9b3.jpg',
      'media/9ffaaeab-b176-43a8-b3d5-da341aaaf7ea.jpg',
      'media/a967ee36-6afc-4755-a328-eb51bcc7ebb4.jpg',
      'media/b2ebad00-454e-4d64-ae4d-1297c8b7d8ed.jpg',
      'media/b7b4d466-603a-4f1c-8945-b7c7387e3428.jpg',
      'media/b82af90e-0c0a-4ceb-b6e5-216f442184a7.jpg',
      'media/b8943cb5-1cd4-4741-a43e-459bfb701a05.jpg',
      'media/bf4b1834-0331-4a28-9aaf-10df2c89e1a9.jpg',
      'media/bf6a75c0-048a-4797-a71e-9ecf98ae9e39.jpg',
      'media/c31ded2c-d3ce-4497-aaf2-53dfc9f51096.jpg',
      'media/c54dd188-973f-4d96-90d6-1bdc89f4e01c.jpg',
      'media/cc093342-e504-4cea-9d77-8a43a4127aed.jpg',
      'media/cfb42886-ee02-4130-a674-05fd017dbe05.jpg',
      'media/d087d88d-ff18-4cd5-b8b5-04d277f7bba2.jpg',
      'media/d1b6b145-be76-43e2-b0d9-11c59bc21ae5.jpg',
      'media/d8e2a66c-39f6-4824-9fa6-5630803baa42.jpg',
      'media/dd8afa85-101f-4052-b3f9-d0908c56c140.jpg',
      'media/e045d0c5-fc09-4836-9a06-dd4034355c12.jpg',
      'media/e161e95a-c5b0-427a-b151-ada722fb73d0.jpg',
      'media/e537a44b-69ce-43a3-a6c7-415630e1e93e.jpg',
      'media/e5b2c621-a1ea-43c2-b437-75032d175530.jpg',
      'media/f0f7e18a-b2e6-4bd1-9164-58fc7fadb57a.jpg',
      'media/f5492b5e-5b72-49aa-b5ea-07ec17e448f4.jpg',
      'media/f8120372-6773-4817-aa47-b1663915cc6f.jpg',
      'media/f93f3627-5cf4-41f1-960d-e70b40a888fd.jpg',
      'media/fd0b0988-d986-4e0e-87d5-77a7727ed61a.jpg',
    ],
    /* GALLERY:END */
  },

  /* ---- BIRTHDAY MESSAGE ------------------------------------------------ */
  message: {
    heading: 'MESSAGE',
    boxTitle: 'FOR YOU',
    /* Typing speed, in milliseconds per character. Bigger = slower.
     * 22 is brisk, 45 is a gentle read, 70 is very slow.                  */
    typeSpeed: 45,
    /* Each string is one page of the dialogue box.
     * Keep pages short-ish so they fit nicely on a phone.                   */
    pages: [
      "Happy birthday, Aleckkk!\n\nI hope you're having a really good day today and that you get to enjoy every moment of it. You deserve all the good things, not just today but every day.",
      "Honestly, I don't even know how to start this message HAHAHA.\n\nI just know that I wanted to make something special for you, kahit simple lang, because you're someone who's really special to me.",
      "I'm really glad that I got to know you. Out of all the people I could've met, somehow I ended up meeting you, and I'm genuinely thankful for that.",
      "I love our conversations, our random talks, our banters, and even those little moments na wala naman tayong importanteng pinag-uusapan pero masaya pa rin.\n\nYou somehow make my days a little better just by being there.",
      "I know we're far from each other, but I hope you know that distance doesn't make you any less important to me.",
      "I hope this year brings you more happiness, more opportunities, more reasons to smile, and everything you've been wishing for.\n\nI hope you continue doing the things you love and become the person you want to be.",
      "And whenever things get hard, I hope you remember that you're doing better than you think you are.\n\nDon't be too hard on yourself, okay?",
      "I also hope that this little website I made makes you smile kahit konti.\n\nI spent time making this because I wanted to give you something that isn't just another \"Happy Birthday\" message.",
      "I wanted you to have something you can look back on someday and remember that there was someone who genuinely appreciated you this much.",
      "So again...\n\nHappy birthday, Aleck!\n\nThank you for being you.",
      "Thank you for all the conversations, laughs, banters, and memories we've made from afar.\n\nI'm really happy I met you.",
      "And honestly...\n\nI hope I get to be part of many more birthdays you'll celebrate.\n\nEnjoy your day, birthday girl. You deserve it.",
    ],
    /* Leave '' and nothing is shown. Put your name here to sign it off. */
    signoff: '',
  },

  /* ---- SONG DEDICATION ------------------------------------------------- */
  song: {
    heading: 'OUR SONG',
    title: 'APHRODITE',
    artist: 'THE RIDLEYS',
    album: 'FOR ALECK',
    /* Drop the mp3 into public/media/ with this exact filename and it plays. */
    file: 'media/aphrodite.mp3',
    /* Her photo doubles as the album art. Same folder, same filename rule.  */
    cover: 'media/aleck.jpg',
    /* Only used before the mp3 exists — real length is read from the file.  */
    duration: 214,

    /* The dedication letter. One string per paragraph.
     * A paragraph wrapped in "double quotes" renders as a big pull quote.   */
    dedicationLabel: 'WHY I CHOSE THIS SONG',
    dedication: [
      "Hiii teee, I chose this song for you kasi every time I listen to it, ikaw talaga naiisip ko HAHAHA.",
      "I don't really know how to explain it, pero I feel like the song fits how I see you.",
      "The song is about being so amazed by someone and seeing them as someone really beautiful and special. And yung title mismo na \"Aphrodite\", which is the goddess of love and beauty, made me think of you.",
      "Not just because you're pretty ha",
      "I mean, yes, you're really really pretty, pero it's also the little things about you that I like. Your personality, your humor, the way you think, your voice, how you treat me, and even the random things you do. I don't know, I just really like those things about you.",
      "There's a part of the song that says \"You're my Aphrodite\", and honestly, that's the part that made me want to dedicate this song to you.",
      "Kasi in my own way, that's how I see you.",
      "Someone who's really beautiful to me, someone I admire a lot, and someone who somehow became really important to me even though we're far from each other.",
      "And I think that's what I like about this song. It doesn't feel like it's only talking about someone's looks. It's more about being completely fascinated by someone.",
      "And I think that's what happened to me with you.",
      "I didn't really plan on liking you this much HAHAHA. It just kinda happened. The more I got to know you, the more things I found to like about you.",
      "And now here I am, making an entire birthday website for you",
      "So yeah...",
      "If you ever ask me why I chose Aphrodite, it's because when I listen to it, I think about you.",
      "And I hope whenever you listen to it too, kahit once lang, you remember that there's someone who's really happy that he got to know you.",
      "Happy birthday, Bff Aleck.",
      "This one's for you.",
      "\"And yes, you're my Aphrodite.\"",
    ],

    /* No lyrics on this one. To turn the lyrics panel back on, add lines here
     * and it reappears automatically:
     *   { t: 0, line: 'first line' },   // t = the second that line starts
     * An empty list means no panel at all.                                  */
    lyrics: [],
  },

  /* ---- THE REASONS ------------------------------------------------------ */
  reasons: {
    /* Leave '' and the heading counts the list for you, so the title can
     * never disagree with the number of tiles on screen.                  */
    heading: '',
    sub: 'TAP A TILE TO UNLOCK IT',
    finished: 'YOU FOUND THEM ALL.',
    finishedSub: 'AND THERE ARE STILL MORE THAN THIS.',

    /* The closing note, shown in full underneath the grid.
     * A paragraph wrapped in "double quotes" becomes a pull quote.        */
    letterLabel: 'AND ONE MORE THING',
    letter: [
      "\"I like you, Aleck. That's probably the simplest reason of all.\"",
      "And honestly, kahit gumawa pa ako ng thousands of reasons, feeling ko kulang pa rin. There's still so many reasons in my mind why I like you, and I know I'll probably keep finding more as I get to know you.",
      "Kasi hindi naman talaga natatapos sa mga bagay na kaya kong ilista yung dahilan kung bakit kita gusto. It's not just your smile, your voice, your personality, or all those little things I mentioned. It's you as a whole.",
      "Somehow, you became someone I genuinely look forward to every day. Someone I miss even after we just talked. Someone whose messages I secretly wait for. Someone who can make me smile without even trying.",
      "And maybe that's what makes you different.",
      "I didn't fall for one specific thing about you. I think I slowly fell for all the little things that make you you.",
      "For the random chikas.\nFor the pang-aasar.\nFor the late-night conversations.\nFor the laughs.\nFor the ML games kahit puro LS.\nFor your random pictures and updates.\nFor your \"hi te.\"\nFor the moments when you're sweet.\nAnd for the other moments with you",
      "I fell for all of it.",
      "And if someday I run out of things to write, it doesn't mean I've run out of reasons to like you. It probably just means there are some feelings that words can't really explain.",
      "So if you ever wonder why I made all of this for you, it's simply because you're someone worth the effort.",
      "Someone I want to appreciate.",
      "Someone I want to make happy.",
      "Someone I'm genuinely grateful I met.",
      "And even though we're far from each other, you've somehow managed to become a part of my everyday life, my thoughts, and honestly, a little part of my heart too.",
      "So yeah, Aleck...",
      "These aren't just 101 reasons why I like you. They're 101 reasons I noticed, but there are still so many more that I haven't put into words yet.",
      "And maybe that's okay, because I don't think I'll ever stop finding new reasons to like you.",
      "I like you, Aleck. More than I planned to, more than I expected to, and probably more than I know how to explain.",
      "And if you ask me for one final reason, it's simply because you're you. And somehow, that's already more than enough for me.",
    ],

    list: [
      "I like how the way you treat me",
      "I like how happy i am with you",
      "I like how we banter lalo na sa ml",
      "I like your sense of maturity",
      "I like how you think",
      "I like your sense of humor",
      "I like how comfortable I am with you",
      "I like your personality",
      "I like your voiceee",
      "I like your \"hi te\"",
      "I like how genuine you are",
      "I like how you dance HAHAHHAHAH",
      "I like how you are good at mo especially selena (pati ako napana mo)",
      "I like how you send random pics and vids",
      "I like your cheeks, pakurot please :<",
      "I like pano mo ko asarin at bully-hin HAHAHHAHA",
      "I like how you are kind of me (opo mabait ka)",
      "I like your random chikas",
      "I like your updates (inaantay ko lagi chats mo)",
      "I like how you appreciate me :<",
      "I like how you boost my confidence",
      "I like you because you're so prettyyyy",
      "I like your eyesss ateee koo",
      "I like your ears, nakita ko yon ang cuteee :>",
      "I like your kilayyy, palit tayo please",
      "I like your katakawan, nagagaya na ako sayo",
      "I like our late nights conversation",
      "I like your kalandian (more please HAHAHHA)",
      "I like your cuteness, wth you're so veryy cuteee",
      "I like your laugh, nakakakilig super",
      "I like your sweet messages (ganto sana palagi HAHAHHA)",
      "I like your presence (sana hindi ka mang ghost HAHAHAHA)",
      "I like how I can rely on you anytime (ikaw din dapat ha)",
      "I like how you are good at drawing (naiinggit ako sayo dito promise)",
      "I like how you interact with elaine (lagi ka nya tinatanong sakin)",
      "I like your mestizaa skin (kainggit btw pref ko talaga sa girl yon)",
      "I like how namimiss kita kahit kakakausap lang natin (miss kita palagi)",
      "I like your random thoughts HAHAHA minsan di ko alam saan mo napupulot",
      "I like how you make our conversations never boring",
      "I like your lasing moments, kahit inaaway mo ko HAHAHHAHA",
      "I like how I get excited kapag nakikita ko pangalan mo sa notifications (pag may nag notif sakin wish ko na sana sayo galing yon HAHAHHA)",
      "I like discovering new things about you everyday",
      "I like your reactions kapag inaasar kita (aasarin pa kita palagi :>)",
      "I like how happy and enjoy we are sa paglalaro kahit lagi tayong ls",
      "I like how you didn't ghost me or sinisisi sa mga errors ko sa game or pag ls tayo",
      "I like our random baliw moments sa ml HAHHAHAH",
      "I like how you make me feel included kahit malayo tayo",
      "I like how you somehow became part of my everyday routine (sana habang buhay na to HAHAHHA)",
      "I like how I look forward to our conversations every day",
      "I like how one message from you can instantly make my mood better",
      "I like how I can talk to you about random things without worrying if it's boring",
      "I like how you understand my humor kahit minsan ang corny ko",
      "I like how you listen on my stories",
      "I like hearing stories about your day",
      "I like learning about the things you love",
      "I like how your messages sometimes stay in my mind for the whole day",
      "I like how I get excited whenever we're about to play together",
      "I like how you make me feel like I matter to you",
      "I like how you make me feel cared for without even realizing it",
      "I like how somehow, I started looking for you in my notifications",
      "I like how you make me feel appreciated even in the smallest ways",
      "I like how I can be myself around you",
      "I like how you make distance feel a little less distant",
      "I like how you still give me butterflies kahit simpleng \"hi\" lang",
      "I like how I smile at my phone like an idiot because of you (araw-araw ako nakangiti dahil sayo fr)",
      "I like how you don't even know how much effect your messages have on me",
      "I like how one sweet message from you can ruin my pagiging nonchalant HAHAHAHA",
      "I like how you make me want to be sweeter kahit hindi naman talaga ako ganon",
      "I like how you bring out the clingy side of me",
      "I like how you make me want to keep talking even when it's already super late",
      "I like how you don't even have to try to make me like you",
      "I like how you became part of my day without me even noticing it",
      "I like how I want to be someone you can always talk to",
      "I like how I want to be there for you even from far away",
      "I like how your happiness somehow makes me happy too",
      "I like how I feel lucky whenever you choose to spend your time talking to me",
      "I like how I can imagine us making even more random memories together",
      "I like how I want to keep knowing you, even after I've already learned so much about you",
      "I like how I still get curious about you every single day",
      "I like how you became one of my favorite people to talk to",
      "I like how I don't need a reason to miss you, I just do always",
      "I like how you make me feel like I can tell you anything",
      "I like how I pretend to be annoyed but secretly enjoy it",
      "I like how you're probably the only person I wouldn't mind bullying me everyday",
      "I like how I could probably compliment you all day and still have more to say (superr ganda mo kasii)",
      "I like how you send pictures without knowing how cute you look in them",
      "I like how I secretly look forward to hearing your voice",
      "I like how you don't make me feel weird for being soft around you",
      "I like how I become extra caring whenever it comes to you",
      "I like how I genuinely want good things to happen to you (praying for it always)",
      "I like how I want to support you kahit sa maliliit na bagay (number 1 supporter mo po ako)",
      "I like how I can be having the worst day and still smile because of you",
      "I like how I never feel like I have to impress you",
      "I like how I can just be myself and you still stay",
      "I like how I can laugh at myself around you",
      "I like how every conversation gives me another reason to appreciate you",
      "I like how one day I realized, \"Ay, gusto ko na talaga ikaw.\" HAHAHAHA",
      "I like how I wasn't expecting to like you this much",
      "I like how you are worth all the effort I put into this",
      "I like how meeting you became one of my favorite unexpected things",
      "I like how you're someone I don't want to lose from my life",
      "I like how after all these reasons, I still can't completely explain why I like you this much.",
    ],
  },

  /* ---- SHARED UI WORDS ------------------------------------------------- */
  ui: {
    back: 'BACK',
    close: 'CLOSE',
  },
};

export default content;
